// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scorecard.Api.Infrastructure.Database;

#nullable disable

namespace Scorecard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807143708_RelabelLabourFactorAndRetireUsdPayrolls")]
    partial class RelabelLabourFactorAndRetireUsdPayrolls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scorecard.Api.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<short>("Market")
                        .HasColumnType("smallint")
                        .HasColumnName("market");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_symbol");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.AssetCurrencyExposure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<short>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.HasKey("Id")
                        .HasName("pk_asset_currency_exposures");

                    b.HasIndex("AssetId", "CurrencyCode")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_currency_exposures_asset_id_currency_code");

                    b.ToTable("asset_currency_exposures", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.AssetFactorScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetScoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_score_id");

                    b.Property<decimal>("Contribution")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("contribution");

                    b.Property<string>("ExplanationEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation_en");

                    b.Property<string>("ExplanationMn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation_mn");

                    b.Property<string>("FactorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("factor_code");

                    b.Property<short?>("NormalizedScore")
                        .HasColumnType("smallint")
                        .HasColumnName("normalized_score");

                    b.Property<short>("Polarity")
                        .HasColumnType("smallint")
                        .HasColumnName("polarity");

                    b.Property<string>("RawLabelEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("raw_label_en");

                    b.Property<string>("RawLabelMn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("raw_label_mn");

                    b.Property<decimal?>("RawValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("raw_value");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_asset_factor_scores");

                    b.HasIndex("AssetScoreId")
                        .HasDatabaseName("ix_asset_factor_scores_asset_score_id");

                    b.ToTable("asset_factor_scores", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.AssetScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<short>("Bias")
                        .HasColumnType("smallint")
                        .HasColumnName("bias");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<int>("CalculationDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("calculation_duration_ms");

                    b.Property<decimal>("Coverage")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("coverage");

                    b.Property<DateTimeOffset>("DataAsOf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_as_of");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("engine_version");

                    b.Property<bool>("IsSufficient")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sufficient");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("integer")
                        .HasColumnName("profile_version");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<Guid>("ScoringProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_asset_scores");

                    b.HasIndex("CalculatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_asset_scores_sufficient_calculated_at")
                        .HasFilter("is_sufficient");

                    b.HasIndex("ScoringProfileId")
                        .HasDatabaseName("ix_asset_scores_scoring_profile_id");

                    b.HasIndex("AssetId", "CalculatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_asset_scores_asset_id_calculated_at");

                    b.ToTable("asset_scores", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.Factor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<short>("Scope")
                        .HasColumnType("smallint")
                        .HasColumnName("scope");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("short_name");

                    b.HasKey("Id")
                        .HasName("pk_factors");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_factors_code");

                    b.ToTable("factors", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.Indicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BandMajor")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("band_major");

                    b.Property<decimal>("BandMinor")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("band_minor");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<short>("CurrencyDirection")
                        .HasColumnType("smallint")
                        .HasColumnName("currency_direction");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<string>("FactorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("factor_code");

                    b.Property<string>("HowItAffects")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("how_it_affects");

                    b.Property<short>("Impact")
                        .HasColumnType("smallint")
                        .HasColumnName("impact");

                    b.Property<bool>("IsProxy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_proxy");

                    b.Property<int>("MaxAgeDays")
                        .HasColumnType("integer")
                        .HasColumnName("max_age_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("ProviderSeriesId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_series_id");

                    b.Property<short>("Transform")
                        .HasColumnType("smallint")
                        .HasColumnName("transform");

                    b.Property<short>("Unit")
                        .HasColumnType("smallint")
                        .HasColumnName("unit");

                    b.Property<string>("WhyItMatters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("why_it_matters");

                    b.HasKey("Id")
                        .HasName("pk_indicators");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_indicators_code");

                    b.HasIndex("FactorCode")
                        .HasDatabaseName("ix_indicators_factor_code");

                    b.ToTable("indicators", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.IndicatorRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Actual")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("actual");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<decimal?>("Forecast")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("forecast");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<Guid>("IndicatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("indicator_id");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<decimal?>("Previous")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("previous");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_ref");

                    b.HasKey("Id")
                        .HasName("pk_indicator_releases");

                    b.HasIndex("CurrencyCode", "ReleasedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_indicator_releases_currency_code_released_at");

                    b.HasIndex("IndicatorId", "CurrencyCode", "Period", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_indicator_releases_indicator_id_currency_code_period_revisi");

                    b.ToTable("indicator_releases", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.IndicatorSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Cadence")
                        .HasColumnType("smallint")
                        .HasColumnName("cadence");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<Guid>("IndicatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("indicator_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<short>("Provider")
                        .HasColumnType("smallint")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSeriesId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_series_id");

                    b.Property<short>("Transform")
                        .HasColumnType("smallint")
                        .HasColumnName("transform");

                    b.HasKey("Id")
                        .HasName("pk_indicator_sources");

                    b.HasIndex("IndicatorId", "CurrencyCode")
                        .IsUnique()
                        .HasDatabaseName("ix_indicator_sources_indicator_id_currency_code");

                    b.ToTable("indicator_sources", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.MarketSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Cadence")
                        .HasColumnType("smallint")
                        .HasColumnName("cadence");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<string>("FactorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("factor_code");

                    b.Property<short>("Frequency")
                        .HasColumnType("smallint")
                        .HasColumnName("frequency");

                    b.Property<int>("MaxAgeDays")
                        .HasColumnType("integer")
                        .HasColumnName("max_age_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("ProviderSeriesId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider_series_id");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<short>("Unit")
                        .HasColumnType("smallint")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_market_series");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_market_series_code");

                    b.ToTable("market_series", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.ProfileWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FactorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("factor_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<short>("Polarity")
                        .HasColumnType("smallint")
                        .HasColumnName("polarity");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_profile_weights");

                    b.HasIndex("ProfileId", "FactorCode")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_weights_profile_id_factor_code");

                    b.ToTable("profile_weights", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.ScoringProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BearishThreshold")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("bearish_threshold");

                    b.Property<decimal>("BullishThreshold")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("bullish_threshold");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<short>("Market")
                        .HasColumnType("smallint")
                        .HasColumnName("market");

                    b.Property<decimal>("MinCoverage")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("min_coverage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_scoring_profiles");

                    b.HasIndex("Market")
                        .IsUnique()
                        .HasDatabaseName("ux_scoring_profiles_active_per_market")
                        .HasFilter("is_active");

                    b.HasIndex("Market", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_scoring_profiles_market_version");

                    b.ToTable("scoring_profiles", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.SeriesObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_series_observations");

                    b.HasIndex("SeriesId", "ObservedAt")
                        .IsUnique()
                        .HasDatabaseName("ix_series_observations_series_id_observed_at");

                    b.ToTable("series_observations", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.SyncSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Cadence")
                        .HasColumnType("smallint")
                        .HasColumnName("cadence");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTimeOffset?>("LastChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_change_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<DateTimeOffset>("NextDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_at");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_code");

                    b.Property<string>("SourceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("source_currency");

                    b.Property<short>("SourceKind")
                        .HasColumnType("smallint")
                        .HasColumnName("source_kind");

                    b.HasKey("Id")
                        .HasName("pk_sync_schedules");

                    b.HasIndex("NextDueAt")
                        .HasDatabaseName("ix_sync_schedules_next_due_at")
                        .HasFilter("is_enabled");

                    b.HasIndex("SourceKind", "SourceCode", "SourceCurrency")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_schedules_source_kind_source_code_source_currency");

                    b.ToTable("sync_schedules", (string)null);
                });

            modelBuilder.Entity("Scorecard.Api.Domain.AssetCurrencyExposure", b =>
                {
                    b.HasOne("Scorecard.Api.Domain.Asset", "Asset")
                        .WithMany("Exposures")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_currency_exposures_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.AssetFactorScore", b =>
                {
                    b.HasOne("Scorecard.Api.Domain.AssetScore", "AssetScore")
                        .WithMany("Factors")
                        .HasForeignKey("AssetScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_factor_scores_asset_scores_asset_score_id");

                    b.Navigation("AssetScore");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.AssetScore", b =>
                {
                    b.HasOne("Scorecard.Api.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_scores_assets_asset_id");

                    b.HasOne("Scorecard.Api.Domain.ScoringProfile", "ScoringProfile")
                        .WithMany()
                        .HasForeignKey("ScoringProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_scores_scoring_profiles_scoring_profile_id");

                    b.Navigation("Asset");

                    b.Navigation("ScoringProfile");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.IndicatorRelease", b =>
                {
                    b.HasOne("Scorecard.Api.Domain.Indicator", "Indicator")
                        .WithMany()
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_indicator_releases_indicators_indicator_id");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.IndicatorSource", b =>
                {
                    b.HasOne("Scorecard.Api.Domain.Indicator", "Indicator")
                        .WithMany("Sources")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_indicator_sources_indicators_indicator_id");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.ProfileWeight", b =>
                {
                    b.HasOne("Scorecard.Api.Domain.ScoringProfile", "Profile")
                        .WithMany("Weights")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_weights_scoring_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.SeriesObservation", b =>
                {
                    b.HasOne("Scorecard.Api.Domain.MarketSeries", "Series")
                        .WithMany("Observations")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_series_observations_market_series_series_id");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.Asset", b =>
                {
                    b.Navigation("Exposures");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.AssetScore", b =>
                {
                    b.Navigation("Factors");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.Indicator", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.MarketSeries", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Scorecard.Api.Domain.ScoringProfile", b =>
                {
                    b.Navigation("Weights");
                });
#pragma warning restore 612, 618
        }
    }
}
